# Site
title:              Gengxin
bio:                'This Is A New Try'
description:        "Gengxin-Zhang, 张同学\n，\n历城二中52级在校生"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
default_background: true
background:         'http://images2015.cnblogs.com/blog/831801/201609/831801-20160902151315121-159677909.jpg'
about_background:   'http://images2015.cnblogs.com/blog/831801/201609/831801-20160902151328168-994691769.jpg'
page_background:    'http://images2015.cnblogs.com/blog/831801/201609/831801-20160902151319433-539227312.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://zhangone.top

# Jekyll
permalink:          /posts/:year/:month/:day/:title
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:             zhgx3ng@outlook.com
#twitter:            username
#facebook:           username
github:             Gengxin-Zhang
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              zhangone
#dribbble:          username
#youtube:           username
#soundcloud:        username
weibo:              zhgx3ng
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
bilibili:           22931083/
#zhihu:              zhang-tong-xue-56-23

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
